import 'design_token.dart';

const defaultDesignTokens = <DesignToken>[
  DesignToken(
    tokenKey: 'color.primary',
    tokenValue: '#6750A4',
    tokenType: DesignTokenType.color,
    groupName: 'boopi',
    description: 'Main Boopi action color.',
    sortOrder: 0,
    isActive: true,
  ),
  DesignToken(
    tokenKey: 'color.on-primary',
    tokenValue: '#FFFFFF',
    tokenType: DesignTokenType.color,
    groupName: 'boopi',
    description: 'Content color on primary surfaces.',
    sortOrder: 1,
    isActive: true,
  ),
  DesignToken(
    tokenKey: 'color.primary-container',
    tokenValue: '#EADDFF',
    tokenType: DesignTokenType.color,
    groupName: 'boopi',
    description: 'Primary container color.',
    sortOrder: 2,
    isActive: true,
  ),
  DesignToken(
    tokenKey: 'color.on-primary-container',
    tokenValue: '#21005D',
    tokenType: DesignTokenType.color,
    groupName: 'boopi',
    description: 'Content color on primary containers.',
    sortOrder: 3,
    isActive: true,
  ),
  DesignToken(
    tokenKey: 'color.secondary',
    tokenValue: '#625B71',
    tokenType: DesignTokenType.color,
    groupName: 'boopi',
    description: 'Secondary color.',
    sortOrder: 4,
    isActive: true,
  ),
  DesignToken(
    tokenKey: 'color.on-secondary',
    tokenValue: '#FFFFFF',
    tokenType: DesignTokenType.color,
    groupName: 'boopi',
    description: 'Content color on secondary surfaces.',
    sortOrder: 5,
    isActive: true,
  ),
  DesignToken(
    tokenKey: 'color.secondary-container',
    tokenValue: '#E8DEF8',
    tokenType: DesignTokenType.color,
    groupName: 'boopi',
    description: 'Secondary container color.',
    sortOrder: 6,
    isActive: true,
  ),
  DesignToken(
    tokenKey: 'color.on-secondary-container',
    tokenValue: '#1D192B',
    tokenType: DesignTokenType.color,
    groupName: 'boopi',
    description: 'Content color on secondary containers.',
    sortOrder: 7,
    isActive: true,
  ),
  DesignToken(
    tokenKey: 'color.surface',
    tokenValue: '#FFFBFE',
    tokenType: DesignTokenType.color,
    groupName: 'boopi',
    description: 'Default surface color.',
    sortOrder: 8,
    isActive: true,
  ),
  DesignToken(
    tokenKey: 'color.on-surface',
    tokenValue: '#1C1B1F',
    tokenType: DesignTokenType.color,
    groupName: 'boopi',
    description: 'Default content color on surfaces.',
    sortOrder: 9,
    isActive: true,
  ),
  DesignToken(
    tokenKey: 'color.surface-variant',
    tokenValue: '#E7E0EC',
    tokenType: DesignTokenType.color,
    groupName: 'boopi',
    description: 'Variant surface color.',
    sortOrder: 10,
    isActive: true,
  ),
  DesignToken(
    tokenKey: 'color.on-surface-variant',
    tokenValue: '#49454F',
    tokenType: DesignTokenType.color,
    groupName: 'boopi',
    description: 'Content color on variant surfaces.',
    sortOrder: 11,
    isActive: true,
  ),
  DesignToken(
    tokenKey: 'color.outline',
    tokenValue: '#79747E',
    tokenType: DesignTokenType.color,
    groupName: 'boopi',
    description: 'Outline and border color.',
    sortOrder: 12,
    isActive: true,
  ),
  DesignToken(
    tokenKey: 'color.error',
    tokenValue: '#B3261E',
    tokenType: DesignTokenType.color,
    groupName: 'boopi',
    description: 'Error color.',
    sortOrder: 13,
    isActive: true,
  ),
  DesignToken(
    tokenKey: 'home.background.top',
    tokenValue: '#24325F',
    tokenType: DesignTokenType.color,
    groupName: 'home',
    description: 'Home background top gradient color.',
    sortOrder: 14,
    isActive: true,
  ),
  DesignToken(
    tokenKey: 'home.background.middle',
    tokenValue: '#324582',
    tokenType: DesignTokenType.color,
    groupName: 'home',
    description: 'Home background middle gradient color.',
    sortOrder: 15,
    isActive: true,
  ),
  DesignToken(
    tokenKey: 'home.background.bottom',
    tokenValue: '#17234F',
    tokenType: DesignTokenType.color,
    groupName: 'home',
    description: 'Home background bottom gradient color.',
    sortOrder: 16,
    isActive: true,
  ),
  DesignToken(
    tokenKey: 'player.background.primary',
    tokenValue: '#58AAF0',
    tokenType: DesignTokenType.color,
    groupName: 'player',
    description: 'Primary player background color.',
    sortOrder: 17,
    isActive: true,
  ),
  DesignToken(
    tokenKey: 'home.card.text.primary',
    tokenValue: '#FFFFFF',
    tokenType: DesignTokenType.color,
    groupName: 'home',
    description: 'Primary text color on home cards.',
    sortOrder: 18,
    isActive: true,
  ),
  DesignToken(
    tokenKey: 'color.primary',
    tokenValue: '#D0BCFF',
    tokenType: DesignTokenType.color,
    theme: DesignTokenTheme.dark,
    groupName: 'boopi',
    description: 'Main Boopi action color for dark theme.',
    sortOrder: 0,
    isActive: true,
  ),
  DesignToken(
    tokenKey: 'color.on-primary',
    tokenValue: '#381E72',
    tokenType: DesignTokenType.color,
    theme: DesignTokenTheme.dark,
    groupName: 'boopi',
    description: 'Content color on primary surfaces for dark theme.',
    sortOrder: 1,
    isActive: true,
  ),
  DesignToken(
    tokenKey: 'color.primary-container',
    tokenValue: '#4F378B',
    tokenType: DesignTokenType.color,
    theme: DesignTokenTheme.dark,
    groupName: 'boopi',
    description: 'Primary container color for dark theme.',
    sortOrder: 2,
    isActive: true,
  ),
  DesignToken(
    tokenKey: 'color.on-primary-container',
    tokenValue: '#EADDFF',
    tokenType: DesignTokenType.color,
    theme: DesignTokenTheme.dark,
    groupName: 'boopi',
    description: 'Content color on primary containers for dark theme.',
    sortOrder: 3,
    isActive: true,
  ),
  DesignToken(
    tokenKey: 'color.secondary',
    tokenValue: '#CCC2DC',
    tokenType: DesignTokenType.color,
    theme: DesignTokenTheme.dark,
    groupName: 'boopi',
    description: 'Secondary color for dark theme.',
    sortOrder: 4,
    isActive: true,
  ),
  DesignToken(
    tokenKey: 'color.on-secondary',
    tokenValue: '#332D41',
    tokenType: DesignTokenType.color,
    theme: DesignTokenTheme.dark,
    groupName: 'boopi',
    description: 'Content color on secondary surfaces for dark theme.',
    sortOrder: 5,
    isActive: true,
  ),
  DesignToken(
    tokenKey: 'color.secondary-container',
    tokenValue: '#4A4458',
    tokenType: DesignTokenType.color,
    theme: DesignTokenTheme.dark,
    groupName: 'boopi',
    description: 'Secondary container color for dark theme.',
    sortOrder: 6,
    isActive: true,
  ),
  DesignToken(
    tokenKey: 'color.on-secondary-container',
    tokenValue: '#E8DEF8',
    tokenType: DesignTokenType.color,
    theme: DesignTokenTheme.dark,
    groupName: 'boopi',
    description: 'Content color on secondary containers for dark theme.',
    sortOrder: 7,
    isActive: true,
  ),
  DesignToken(
    tokenKey: 'color.surface',
    tokenValue: '#141218',
    tokenType: DesignTokenType.color,
    theme: DesignTokenTheme.dark,
    groupName: 'boopi',
    description: 'Default surface color for dark theme.',
    sortOrder: 8,
    isActive: true,
  ),
  DesignToken(
    tokenKey: 'color.on-surface',
    tokenValue: '#E6E0E9',
    tokenType: DesignTokenType.color,
    theme: DesignTokenTheme.dark,
    groupName: 'boopi',
    description: 'Default content color on dark surfaces.',
    sortOrder: 9,
    isActive: true,
  ),
  DesignToken(
    tokenKey: 'color.surface-variant',
    tokenValue: '#49454F',
    tokenType: DesignTokenType.color,
    theme: DesignTokenTheme.dark,
    groupName: 'boopi',
    description: 'Variant surface color for dark theme.',
    sortOrder: 10,
    isActive: true,
  ),
  DesignToken(
    tokenKey: 'color.on-surface-variant',
    tokenValue: '#CAC4D0',
    tokenType: DesignTokenType.color,
    theme: DesignTokenTheme.dark,
    groupName: 'boopi',
    description: 'Content color on variant dark surfaces.',
    sortOrder: 11,
    isActive: true,
  ),
  DesignToken(
    tokenKey: 'color.outline',
    tokenValue: '#938F99',
    tokenType: DesignTokenType.color,
    theme: DesignTokenTheme.dark,
    groupName: 'boopi',
    description: 'Outline and border color for dark theme.',
    sortOrder: 12,
    isActive: true,
  ),
  DesignToken(
    tokenKey: 'color.error',
    tokenValue: '#F2B8B5',
    tokenType: DesignTokenType.color,
    theme: DesignTokenTheme.dark,
    groupName: 'boopi',
    description: 'Error color for dark theme.',
    sortOrder: 13,
    isActive: true,
  ),
  DesignToken(
    tokenKey: 'home.background.top',
    tokenValue: '#24325F',
    tokenType: DesignTokenType.color,
    theme: DesignTokenTheme.dark,
    groupName: 'home',
    description: 'Home background top gradient color for dark theme.',
    sortOrder: 14,
    isActive: true,
  ),
  DesignToken(
    tokenKey: 'home.background.middle',
    tokenValue: '#324582',
    tokenType: DesignTokenType.color,
    theme: DesignTokenTheme.dark,
    groupName: 'home',
    description: 'Home background middle gradient color for dark theme.',
    sortOrder: 15,
    isActive: true,
  ),
  DesignToken(
    tokenKey: 'home.background.bottom',
    tokenValue: '#17234F',
    tokenType: DesignTokenType.color,
    theme: DesignTokenTheme.dark,
    groupName: 'home',
    description: 'Home background bottom gradient color for dark theme.',
    sortOrder: 16,
    isActive: true,
  ),
  DesignToken(
    tokenKey: 'player.background.primary',
    tokenValue: '#58AAF0',
    tokenType: DesignTokenType.color,
    theme: DesignTokenTheme.dark,
    groupName: 'player',
    description: 'Primary player background color for dark theme.',
    sortOrder: 17,
    isActive: true,
  ),
  DesignToken(
    tokenKey: 'home.card.text.primary',
    tokenValue: '#FFFFFF',
    tokenType: DesignTokenType.color,
    theme: DesignTokenTheme.dark,
    groupName: 'home',
    description: 'Primary text color on home cards for dark theme.',
    sortOrder: 18,
    isActive: true,
  ),
  DesignToken(
    tokenKey: 'typography.display-large',
    tokenValue:
        '{"size":"57","lineHeight":"1.12","letterSpacing":"-0.25","weight":"400"}',
    tokenType: DesignTokenType.typography,
    groupName: 'typography',
    description: 'Display Large type token for Boopi app screens.',
    sortOrder: 0,
    isActive: true,
  ),
  DesignToken(
    tokenKey: 'typography.display-medium',
    tokenValue:
        '{"size":"45","lineHeight":"1.16","letterSpacing":"0","weight":"400"}',
    tokenType: DesignTokenType.typography,
    groupName: 'typography',
    description: 'Display Medium type token for Boopi app screens.',
    sortOrder: 1,
    isActive: true,
  ),
  DesignToken(
    tokenKey: 'typography.display-small',
    tokenValue:
        '{"size":"36","lineHeight":"1.22","letterSpacing":"0","weight":"400"}',
    tokenType: DesignTokenType.typography,
    groupName: 'typography',
    description: 'Display Small type token for Boopi app screens.',
    sortOrder: 2,
    isActive: true,
  ),
  DesignToken(
    tokenKey: 'typography.headline-large',
    tokenValue:
        '{"size":"32","lineHeight":"1.25","letterSpacing":"0","weight":"400"}',
    tokenType: DesignTokenType.typography,
    groupName: 'typography',
    description: 'Headline Large type token for Boopi app screens.',
    sortOrder: 3,
    isActive: true,
  ),
  DesignToken(
    tokenKey: 'typography.headline-medium',
    tokenValue:
        '{"size":"28","lineHeight":"1.29","letterSpacing":"0","weight":"400"}',
    tokenType: DesignTokenType.typography,
    groupName: 'typography',
    description: 'Headline Medium type token for Boopi app screens.',
    sortOrder: 4,
    isActive: true,
  ),
  DesignToken(
    tokenKey: 'typography.headline-small',
    tokenValue:
        '{"size":"24","lineHeight":"1.33","letterSpacing":"0","weight":"400"}',
    tokenType: DesignTokenType.typography,
    groupName: 'typography',
    description: 'Headline Small type token for Boopi app screens.',
    sortOrder: 5,
    isActive: true,
  ),
  DesignToken(
    tokenKey: 'typography.title-large',
    tokenValue:
        '{"size":"22","lineHeight":"1.27","letterSpacing":"0","weight":"500"}',
    tokenType: DesignTokenType.typography,
    groupName: 'typography',
    description: 'Title Large type token for Boopi app screens.',
    sortOrder: 6,
    isActive: true,
  ),
  DesignToken(
    tokenKey: 'typography.title-medium',
    tokenValue:
        '{"size":"16","lineHeight":"1.5","letterSpacing":"0.15","weight":"500"}',
    tokenType: DesignTokenType.typography,
    groupName: 'typography',
    description: 'Title Medium type token for Boopi app screens.',
    sortOrder: 7,
    isActive: true,
  ),
  DesignToken(
    tokenKey: 'typography.title-small',
    tokenValue:
        '{"size":"14","lineHeight":"1.43","letterSpacing":"0.1","weight":"500"}',
    tokenType: DesignTokenType.typography,
    groupName: 'typography',
    description: 'Title Small type token for Boopi app screens.',
    sortOrder: 8,
    isActive: true,
  ),
  DesignToken(
    tokenKey: 'typography.body-large',
    tokenValue:
        '{"size":"16","lineHeight":"1.5","letterSpacing":"0.5","weight":"400"}',
    tokenType: DesignTokenType.typography,
    groupName: 'typography',
    description: 'Body Large type token for Boopi app screens.',
    sortOrder: 9,
    isActive: true,
  ),
  DesignToken(
    tokenKey: 'typography.body-medium',
    tokenValue:
        '{"size":"14","lineHeight":"1.43","letterSpacing":"0.25","weight":"400"}',
    tokenType: DesignTokenType.typography,
    groupName: 'typography',
    description: 'Body Medium type token for Boopi app screens.',
    sortOrder: 10,
    isActive: true,
  ),
  DesignToken(
    tokenKey: 'typography.body-small',
    tokenValue:
        '{"size":"12","lineHeight":"1.33","letterSpacing":"0.4","weight":"400"}',
    tokenType: DesignTokenType.typography,
    groupName: 'typography',
    description: 'Body Small type token for Boopi app screens.',
    sortOrder: 11,
    isActive: true,
  ),
  DesignToken(
    tokenKey: 'typography.label-large',
    tokenValue:
        '{"size":"14","lineHeight":"1.43","letterSpacing":"0.1","weight":"500"}',
    tokenType: DesignTokenType.typography,
    groupName: 'typography',
    description: 'Label Large type token for Boopi app screens.',
    sortOrder: 12,
    isActive: true,
  ),
  DesignToken(
    tokenKey: 'typography.label-medium',
    tokenValue:
        '{"size":"12","lineHeight":"1.33","letterSpacing":"0.5","weight":"500"}',
    tokenType: DesignTokenType.typography,
    groupName: 'typography',
    description: 'Label Medium type token for Boopi app screens.',
    sortOrder: 13,
    isActive: true,
  ),
  DesignToken(
    tokenKey: 'typography.label-small',
    tokenValue:
        '{"size":"11","lineHeight":"1.45","letterSpacing":"0.5","weight":"500"}',
    tokenType: DesignTokenType.typography,
    groupName: 'typography',
    description: 'Label Small type token for Boopi app screens.',
    sortOrder: 14,
    isActive: true,
  ),
  DesignToken(
    tokenKey: 'preset.button.primary-cta',
    tokenValue:
        '{"background":"#4945FF","foreground":"#FFFFFF","track":"#e0e0e0","radius":"12","padding":"14","fillMode":"solid","trackMode":"none","applicability":["Nudge","Guide"]}',
    tokenType: DesignTokenType.preset,
    groupName: 'Button',
    description: 'Primary CTA button preset.',
    sortOrder: 0,
    isActive: true,
  ),
  DesignToken(
    tokenKey: 'preset.progress-bar.primary',
    tokenValue:
        '{"background":"#ffffff","foreground":"#4945FF","track":"#E0E0E0","radius":"4","padding":"0","fillMode":"solid","trackMode":"solid","applicability":["Nudge","Guide"]}',
    tokenType: DesignTokenType.preset,
    groupName: 'Progress Bar',
    description: 'Progress bar preset.',
    sortOrder: 1,
    isActive: true,
  ),
  DesignToken(
    tokenKey: 'preset.stories.card',
    tokenValue:
        '{"background":"#24325F","foreground":"#FFFFFF","track":"#e0e0e0","radius":"16","padding":"16","fillMode":"solid","trackMode":"none","applicability":["Guide"]}',
    tokenType: DesignTokenType.preset,
    groupName: 'Stories',
    description: 'Story card preset.',
    sortOrder: 2,
    isActive: true,
  ),
  DesignToken(
    tokenKey: 'preset.dialog.surface',
    tokenValue:
        '{"background":"#FFFFFF","foreground":"#1D1B2A","track":"#e0e0e0","radius":"20","padding":"20","fillMode":"solid","trackMode":"none","applicability":["Nudge","Guide"]}',
    tokenType: DesignTokenType.preset,
    groupName: 'Dialog',
    description: 'Dialog surface preset.',
    sortOrder: 3,
    isActive: true,
  ),
  DesignToken(
    tokenKey: 'preset.tooltip.bubble',
    tokenValue:
        '{"background":"#1D1B2A","foreground":"#FFFFFF","track":"#e0e0e0","radius":"8","padding":"10","fillMode":"solid","trackMode":"none","applicability":["Nudge"]}',
    tokenType: DesignTokenType.preset,
    groupName: 'Tooltip',
    description: 'Tooltip bubble preset.',
    sortOrder: 4,
    isActive: true,
  ),
];
